---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: k3s-server-1
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: "/lib/systemd/systemd"
    environment:
      container: docker
    groups:
      - k3s_servers
  - name: k3s-server-2
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: "/lib/systemd/systemd"
    environment:
      container: docker
    groups:
      - k3s_servers
  - name: k3s-server-3
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: "/lib/systemd/systemd"
    environment:
      container: docker
    groups:
      - k3s_servers
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_VERBOSITY: 1
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      k3s_servers:
        k3s_server_testing: true
        k3s_server_cluster_init: true
        k3s_server_token: "test-token-for-cluster"
        k3s_server_cluster_mode: "ha"
verifier:
  name: testinfra
  directory: ../tests
  options:
    v: 1
scenario:
  name: ha-cluster
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
