---
- name: Converge
  hosts: all
  become: true
  vars:
    is_test_mode: true
    test_base_dir: "/tmp/jetson-test"
    jetson_setup_required_locales:
      - "en_US.UTF-8"
    jetson_setup_swap_size: "2G"
    jetson_setup_power_mode: "MAXN"

  pre_tasks:
    - name: Create test directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ test_base_dir }}"
        - "{{ test_base_dir }}/etc/systemd/system"
        - "{{ test_base_dir }}/etc/tegra-power"
        - "{{ test_base_dir }}/usr/local/bin"

  roles:
    - role: jetson_setup

  post_tasks:
    - name: Show test results
      ansible.builtin.debug:
        msg: "Jetson setup role converge completed successfully"
