---
- name: Converge
  hosts: all
  become: true
  vars:
    is_test_mode: true
    test_base_dir: "/tmp/jetson-test"
    jetson_setup_required_locales:
      - "en_US.UTF-8"
    jetson_setup_swap_size: "2G"
    jetson_setup_power_mode: "MAXN"

  pre_tasks:
    - name: Create test directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ test_base_dir }}"
        - "{{ test_base_dir }}/etc/systemd/system"
        - "{{ test_base_dir }}/etc/tegra-power"
        - "{{ test_base_dir }}/usr/local/bin"
        - "/proc/device-tree"

    - name: Create mock device-tree for Jetson detection
      ansible.builtin.copy:
        content: "NVIDIA Jetson AGX Orin"
        dest: "/proc/device-tree/model"
        mode: '0444'

    - name: Create mock nvpmodel tool for testing
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          echo "Mock nvpmodel for testing"
          exit 0
        dest: "/usr/local/bin/nvpmodel"
        mode: '0755'

    - name: Create mock jetson_clocks tool for testing
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          echo "Mock jetson_clocks for testing"
          exit 0
        dest: "/usr/local/bin/jetson_clocks"
        mode: '0755'

  roles:
    - role: jetson_setup

  post_tasks:
    - name: Show test results
      ansible.builtin.debug:
        msg: "Jetson setup role converge completed successfully"
