---
- name: Verify
  hosts: all
  become: true
  vars:
    test_base_dir: "/tmp/jetson-test"

  tasks:
    - name: Check test directory structure
      ansible.builtin.stat:
        path: "{{ item }}"
      register: dir_check
      loop:
        - "{{ test_base_dir }}"
        - "{{ test_base_dir }}/proc/device-tree"
        - "{{ test_base_dir }}/etc/tegra-power"
        - "{{ test_base_dir }}/usr/local/bin"

    - name: Verify directories exist
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.isdir
        fail_msg: "Required directory {{ item.invocation.module_args.path }} not properly created"
        success_msg: "Directory {{ item.invocation.module_args.path }} exists and is valid"
      loop: "{{ dir_check.results }}"

    - name: Check mock files existence
      ansible.builtin.stat:
        path: "{{ item }}"
      register: file_check
      loop:
        - "{{ test_base_dir }}/proc/device-tree/model"
        - "/usr/local/bin/nvpmodel"
        - "/usr/local/bin/jetson_clocks"

    - name: Verify mock files
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.isfile
          - item.stat.mode == '0444' if 'model' in item.invocation.module_args.path else item.stat.mode == '0755'
        fail_msg: "Mock file {{ item.invocation.module_args.path }} not properly created"
        success_msg: "Mock file {{ item.invocation.module_args.path }} exists with correct permissions"
      loop: "{{ file_check.results }}"

    - name: Verify model file content
      ansible.builtin.command: "cat {{ test_base_dir }}/proc/device-tree/model"
      register: model_content
      changed_when: false
      failed_when: model_content.stdout != "NVIDIA Jetson AGX Orin"

    - name: Check if environment variable is set
      ansible.builtin.shell: "grep DEVICE_TREE_PATH /etc/environment"
      register: env_check
      changed_when: false
      failed_when: false

    - name: Verify environment variable
      ansible.builtin.assert:
        that:
          - env_check.rc == 0
          - env_check.stdout is search(test_base_dir + '/proc/device-tree')
        fail_msg: "DEVICE_TREE_PATH environment variable not properly set"
        success_msg: "DEVICE_TREE_PATH environment variable correctly configured"
