[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "homelab-infra"
version = "0.1.0"
description = "Homelab infrastructure as code"
readme = "README.md"
authors = [
    {name = "Samuel Prime", email = "sprime01@gmail.com"}
]
requires-python = ">=3.10"
dependencies = [
    "ansible>=9.0.0",
    "ansible-lint>=24.0.0",
    "netaddr>=1.0.0",
    "jmespath>=1.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.0.0",
    "molecule>=3.0.0",
    "molecule-docker>=2.0.0",
    "docker>=6.0.0",
    "requests>=2.25.0",
    "selinux>=0.3.0",
]

[tool.setuptools]
packages = []

[dependency-groups]
dev = [
    "docker>=7.1.0",
    "molecule>=25.4.0",
    "molecule-docker>=2.1.0",
    "requests>=2.32.3",
]
