[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "homelab-infra"
version = "0.1.0"
description = "Homelab infrastructure as code"
readme = "README.md"
authors = [
    {name = "Samuel Prime", email = "sprime01@gmail.com"}
]
requires-python = ">=3.8"
dependencies = [
    "ansible>=9.0.0",
    "ansible-lint>=24.0.0",
    "netaddr>=1.0.0",
    "jmespath>=1.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.0.0",
]

[tool.setuptools]
# Specify exact packages to include
packages = []  # Empty list means this is not a library package

# OR use find directive to customize discovery
# [tool.setuptools.find]
# include = ["src*"]  # if you moved code to src directory
# exclude = ["ansible*", "kubernetes*", "logs*", "pulumi*"]  # exclude directories you don't want
