---
- name: Restart k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
    daemon_reload: true
  when: not k3s_test_mode

- name: Stop k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: stopped
  when: not k3s_test_mode

- name: Start k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
    enabled: true
  when: not k3s_test_mode
