---
# OS-specific variables for Ubuntu systems
common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - python3-pip
  - vim
  - htop
  - iftop
  - net-tools
  - nmap
  - tcpdump
  - ufw
  - fail2ban
  - unattended-upgrades
  - chrony

common_timezone_package: tzdata
common_ntp_package: chrony
common_ntp_service: chrony
