---
- name: Install UFW
  apt:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure default UFW rules
  ufw:
    state: enabled
    policy: deny
    direction: incoming
  when: ansible_os_family == "Debian" and configure_firewall | bool and not ansible_check_mode
  ignore_errors: "{{ ansible_check_mode }}"

- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH
  when: ansible_os_family == "Debian" and configure_firewall | bool and not ansible_check_mode
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure additional UFW rules
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
  loop: "{{ ufw_rules }}"
  when: ansible_os_family == "Debian" and configure_firewall | bool and ufw_rules is defined and not ansible_check_mode
  ignore_errors: "{{ ansible_check_mode }}"

- name: Log UFW rule configuration status
  ansible.builtin.debug:
    msg: "UFW rule configuration status: {{ item }}"
  loop: "{{ ufw_rules }}"
  when: ansible_os_family == "Debian" and configure_firewall | bool and ufw_rules is defined and not ansible_check_mode

- name: Validate UFW rule configuration
  ansible.builtin.assert:
    that:
      - ufw_rules is defined
      - ufw_rules | length > 0
    fail_msg: "UFW rule configuration failed"
