---
- name: Install NTP
  apt:
    name: "{{ common_ntp_package }}"
    state: present
  when: ansible_os_family == "Debian"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart chrony
  when: ansible_os_family == "Debian"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Enable and start chrony service
  service:
    name: "{{ common_ntp_service }}"
    state: started
    enabled: yes
  when: ansible_os_family == "Debian" and not ansible_check_mode
  ignore_errors: "{{ ansible_check_mode }}"
