---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Upgrade all packages
  apt:
    upgrade: "{{ package_upgrade_type }}"
  when: ansible_os_family == "Debian" and package_upgrade | bool

- name: Autoremove unused packages
  apt:
    autoremove: yes
  when: ansible_os_family == "Debian"
