---
all:
  children:
    homelab:
      children:
        control_nodes:
          hosts:
            beelink:
              ansible_host: "{{ lookup('env', 'BEELINK_HOST') }}"
              ansible_connection: ssh
              ansible_user: "{{ lookup('env', 'BEELINK_USER') }}"
              node_type: "server"
              cpu_cores: "{{ lookup('env', 'BEELINK_CPU_CORES') }}"
              memory_gb: "{{ lookup('env', 'BEELINK_MEMORY_GB') }}"
        ai_nodes:
          hosts:
            jetson:
              ansible_host: "{{ lookup('env', 'JETSON_HOST') }}"
              ansible_connection: ssh
              ansible_user: "{{ lookup('env', 'JETSON_USER') }}"
              node_type: "edge_device"
              cuda_enabled: true
              cpu_cores: "{{ lookup('env', 'JETSON_CPU_CORES') }}"
              memory_gb: "{{ lookup('env', 'JETSON_MEMORY_GB') }}"
              gpu_memory: "{{ lookup('env', 'JETSON_GPU_MEMORY') }}"
              device_tree_path: "{{ lookup('env', 'DEVICE_TREE_PATH') }}"
        home_automation_nodes:
          hosts:
            ha_yellow:
              ansible_host: "{{ lookup('env', 'HA_YELLOW_HOST') }}"
              ansible_connection: ssh
              ansible_user: "{{ lookup('env', 'HA_YELLOW_USER') }}"
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
              node_type: "home_automation"
              zigbee_enabled: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    timezone: "{{ lookup('env', 'TIMEZONE') }}"
