---
all:
  children:
    homelab:
      children:
        control_nodes:
          hosts:
            beelink:
              ansible_host: "{{ beelink_ip }}"
              ansible_connection: ssh
              ansible_user: "{{ beelink_user }}"
              node_type: "{{ beelink_node_type }}"
              cpu_cores: "{{ beelink_cpu_cores }}"
              memory_gb: "{{ beelink_memory_gb }}"
        ai_nodes:
          hosts:
            jetson:
              ansible_host: "{{ jetson_ip }}"
              ansible_connection: ssh
              ansible_user: "{{ jetson_user }}"
              node_type: "{{ jetson_node_type }}"
              cuda_enabled: "{{ jetson_cuda_enabled }}"
              gpu_memory: "{{ jetson_gpu_memory }}"
        home_automation_nodes:
          hosts:
            ha_yellow:
              ansible_host: "{{ ha_yellow_ip }}"
              ansible_connection: ssh
              ansible_user: "{{ ha_yellow_user }}"
              ansible_ssh_common_args: "{{ ha_yellow_ssh_args }}"
              node_type: "{{ ha_yellow_node_type }}"
              zigbee_enabled: "{{ ha_yellow_zigbee_enabled }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    timezone: America/New_York
