---
- name: Add NVIDIA Docker repository (mock in test mode)
  ansible.builtin.debug:
    msg: "Would add NVIDIA Docker repository in real mode"
  when: ansible_check_mode or is_test_mode

- name: Add NVIDIA Docker repository
  ansible.builtin.package:
    name: nvidia-docker
    state: present
  when: not ansible_check_mode and not is_test_mode
