---
- name: Mock container runtime setup (test mode)
  ansible.builtin.debug:
    msg: "Would configure {{ jetson_setup_container_runtime }} runtime in test mode"
  when: ansible_check_mode or is_test_mode

- name: Install container runtime
  ansible.builtin.package:
    name: "{{ jetson_setup_container_runtime }}"
    state: present
  when: not ansible_check_mode and not is_test_mode

- name: Log container runtime installation status
  ansible.builtin.debug:
    msg: "Container runtime installation status: {{ jetson_setup_container_runtime }}"

- name: Validate container runtime installation
  ansible.builtin.assert:
    that:
      - jetson_setup_container_runtime is defined
    fail_msg: "Container runtime installation failed"
