---
- name: Install CUDA repository GPG key
  ansible.builtin.apt_key:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub"
    state: present

- name: Add CUDA repository
  ansible.builtin.apt_repository:
    repo: "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install CUDA toolkit
  ansible.builtin.apt:
    name: "cuda-toolkit-{{ jetson_setup_cuda_version }}"
    state: present

- name: Configure CUDA environment
  ansible.builtin.template:
    src: cuda.sh.j2
    dest: /etc/profile.d/cuda.sh
    mode: "0644"

- name: Update CUDA paths
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'PATH=$PATH:/usr/local/cuda/bin'
    state: present
