---
# Add a variable to determine if we're in test mode
- name: Set test mode variable
  ansible.builtin.set_fact:
    is_test_mode: "{{ is_test_mode | default(false) }}"
  tags: always

# Original hardware check
- name: Check if running on Jetson AGX Orin
  ansible.builtin.command: cat /proc/device-tree/model
  register: jetson_model
  changed_when: false
  failed_when: false
  check_mode: false
  when: not is_test_mode

- name: Fail if not running on Jetson AGX Orin
  ansible.builtin.fail:
    msg: "This role is designed to run only on Jetson AGX Orin devices."
  when: not is_test_mode and (jetson_model.rc != 0 or 'Jetson AGX Orin' not in jetson_model.stdout)

# Continue with the rest of the tasks
- name: Import system configuration tasks
  ansible.builtin.import_tasks: system_config.yml
- name: Import power optimization tasks
  ansible.builtin.import_tasks: power_optimization.yml
- name: Import CUDA setup tasks
  ansible.builtin.import_tasks: cuda_setup.yml
- name: Import ML libraries tasks
  ansible.builtin.import_tasks: ml_libraries.yml
- name: Import container runtime tasks
  ansible.builtin.import_tasks: container_runtime.yml
- name: Import Python ML tasks
  ansible.builtin.import_tasks: python_ml.yml
- name: Import monitoring tasks
  ansible.builtin.import_tasks: monitoring.yml
