---
- name: Install ML libraries
  ansible.builtin.package:
    name: "{{ jetson_setup_ml_libraries }}"
    state: present

- name: Configure ML library paths
  ansible.builtin.template:
    src: ml_paths.conf.j2
    dest: /etc/ld.so.conf.d/nvidia-ml.conf
    mode: "0644"
