---
# Monitoring setup tasks

- name: Install monitoring tools
  apt:
    name:
      - lm-sensors
      - htop
      - iotop
      - nvtop
    state: present
  when: not ansible_check_mode
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure sensors detection
  command: sensors-detect --auto
  when: not ansible_check_mode
  changed_when: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create monitoring service for GPU stats
  template:
    src: gpu-stats.service.j2
    dest: /etc/systemd/system/gpu-stats.service
    mode: '0644'
  when: not ansible_check_mode
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install jtop (Jetson stats)
  pip:
    name: jetson-stats
    state: present
  when: not ansible_check_mode
  ignore_errors: "{{ ansible_check_mode }}"

- name: Enable and start jetson-stats service
  service:
    name: jetson-stats
    state: started
    enabled: yes
  when: not ansible_check_mode
  ignore_errors: "{{ ansible_check_mode }}"
