---
- name: Install monitoring packages
  ansible.builtin.package:
    name: "{{ jetson_setup_monitoring_packages }}"
    state: present
  when: not ansible_check_mode and not is_test_mode

- name: Configure monitoring services (mock in test mode)
  ansible.builtin.debug:
    msg: "Would configure monitoring in real mode"
  when: ansible_check_mode or is_test_mode
