---
- name: Mock power optimization (test mode)
  ansible.builtin.debug:
    msg: "Would configure power settings in real mode"
  when: ansible_check_mode or is_test_mode

- name: Configure power mode
  ansible.builtin.command: nvpmodel -m "{{ jetson_setup_power_mode }}"
  changed_when: true
  when: not ansible_check_mode and not is_test_mode

- name: Enable fan control
  ansible.builtin.service:
    name: nvfancontrol
    state: started
    enabled: true
  when: not ansible_check_mode and not is_test_mode
