---
- name: Mock Python ML setup (test mode)
  ansible.builtin.debug:
    msg: "Would configure Python ML packages in test mode"
  when: ansible_check_mode or is_test_mode

- name: Install Python ML packages
  ansible.builtin.pip:
    name: "{{ jetson_setup_python_ml_packages }}"
    state: present
  when: not ansible_check_mode and not is_test_mode
