---
- name: Mock Python ML setup (test mode)
  ansible.builtin.debug:
    msg: "Would configure Python ML environment in real mode"
  when: ansible_check_mode or is_test_mode

- name: Create Python ML virtualenv (real mode)
  ansible.builtin.pip:
    name: pip
    virtualenv: "{{ ansible_env.HOME }}/.virtualenvs/ml"
    virtualenv_command: python3 -m venv
  when: not ansible_check_mode and not is_test_mode

- name: Install Python ML packages
  ansible.builtin.pip:
    name: "{{ jetson_setup_python_ml_packages }}"
    virtualenv: "{{ ansible_env.HOME }}/.virtualenvs/ml"
  when: not ansible_check_mode and not is_test_mode
  failed_when: false
