---
# System configuration tasks

- name: Generate required locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ jetson_setup_required_locales }}"
  when: not ansible_check_mode

- name: Mock swap file operations (test mode)
  ansible.builtin.debug:
    msg: "Would configure swap in real mode"
  when: ansible_check_mode or is_test_mode

- name: Check if swap file exists
  ansible.builtin.stat:
    path: /swapfile
  register: swap_file_check
  when: not ansible_check_mode and not is_test_mode

- name: Create swap file
  ansible.builtin.command: dd if=/dev/zero of=/swapfile bs=1M count=8192
  args:
    creates: /swapfile
  when: not swap_file_check.stat.exists and not ansible_check_mode and not is_test_mode

- name: Set swap file permissions
  ansible.builtin.file:
    path: /swapfile
    owner: root
    group: root
    mode: "0o600"
  when: not ansible_check_mode and not is_test_mode

- name: Make swap
  ansible.builtin.command: mkswap /swapfile
  when: not ansible_check_mode and not is_test_mode

- name: Enable swap
  ansible.builtin.command: swapon /swapfile
  when: not ansible_check_mode and not is_test_mode

- name: Add swap to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile none swap sw 0 0"
    state: present
  when: not ansible_check_mode and not is_test_mode

- name: Configure system settings
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.d/99-jetson.conf
    mode: "0o644"
  when: not ansible_check_mode and not is_test_mode
