---
# System configuration tasks
- name: Generate required locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ jetson_setup_required_locales }}"
  when: not ansible_check_mode and not is_test_mode

- name: Mock operations for test mode
  ansible.builtin.debug:
    msg: "Would perform system configuration in real mode"
  when: is_test_mode

# Initialize swap_file_check early to prevent issues
- name: Initialize swap_file_check for test mode
  ansible.builtin.set_fact:
    swap_file_check: {'stat': {'exists': false}}
  when: is_test_mode

- name: Check if swap file exists
  ansible.builtin.stat:
    path: /swapfile
  register: swap_file_check
  when: not ansible_check_mode and not is_test_mode

# Skip all real operations if in test mode
- name: Create swap file
  ansible.builtin.command: dd if=/dev/zero of=/swapfile bs=1M count=8192
  args:
    creates: /swapfile
  changed_when: true
  when: not is_test_mode and not ansible_check_mode and not swap_file_check.stat.exists

- name: Set swap file permissions
  ansible.builtin.file:
    path: /swapfile
    owner: root
    group: root
    mode: "0600"
  when: not is_test_mode and not ansible_check_mode

- name: Make swap
  ansible.builtin.command: mkswap /swapfile
  changed_when: true
  when: not is_test_mode and not ansible_check_mode

- name: Enable swap
  ansible.builtin.command: swapon /swapfile
  changed_when: true
  when: not is_test_mode and not ansible_check_mode

- name: Add swap to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile none swap sw 0 0"
    state: present
  when: not is_test_mode and not ansible_check_mode
