---
- name: restart chrony
  service:
    name: chrony
    state: restarted
  when: ansible_os_family == "Debian"

- name: restart ssh
  service:
    name: sshd
    state: restarted
  when: ansible_os_family == "Debian"

- name: restart ufw
  service:
    name: ufw
    state: restarted
  when: ansible_os_family == "Debian"
