# Common variables for all hosts in the homelab group
# Network configuration
beelink_ip: '{{ lookup('env', 'VAULT_BEELINK_USER') }}{{ lookup('env', 'BEELINK_HOST') }}'
jetson_ip: '{{ lookup('env', 'JETSON_HOST') }}'
ha_yellow_ip: '{{ lookup('env', 'HA_YELLOW_HOST') }}'

# Node type definitions
beelink_node_type: server
jetson_node_type: edge_device
ha_yellow_node_type: home_automation

# Hardware specifications
beelink_cpu_cores: '{{ lookup('env', 'BEELINK_CPU_CORES') }}'
beelink_memory_gb: '{{ lookup('env', 'BEELINK_MEMORY_GB') }}'
jetson_cuda_enabled: true
jetson_gpu_memory: 8
ha_yellow_zigbee_enabled: true

# SSH configurations
ha_yellow_ssh_args: '-o StrictHostKeyChecking=no'


# Include vault file with sensitive variables
beelink_user: "{{ lookup('env', 'VAULT_BEELINK_USER') }}"
jetson_user: "{{ lookup('env', 'VAULT_JETSON_USER') }}"
ha_yellow_user: "{{ lookup('env', 'VAULT_HA_YELLOW_USER') }}"

# Pulumi configuration from .env file
pulumi_config_passphrase: "{{ lookup('env', 'PULUMI_CONFIG_PASSPHRASE') }}"
pulumi_backend_url: "{{ lookup('env', 'PULUMI_BACKEND_URL') }}"

# SSH configuration issues fixed
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
