---
# K3s version to install
k3s_server_version: "v1.26.6+k3s1"
k3s_server_release_url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_server_version }}/k3s"

# Service configuration
k3s_server_systemd_dir: "/etc/systemd/system"
k3s_server_service_name: "k3s"

# K3s install options
k3s_server_install_dir: "/usr/local/bin"
k3s_server_config_dir: "/etc/rancher/k3s"
k3s_server_config_file: "{{ k3s_server_config_dir }}/config.yaml"
k3s_server_kubeconfig_file: "/etc/rancher/k3s/k3s.yaml"
k3s_server_kubeconfig_mode: "0644"
k3s_server_token_file: "/var/lib/rancher/k3s/server/node-token"  # This is the correct path per k3s default
k3s_server_data_dir: "/var/lib/rancher/k3s"

# Disable components that we don't need or will replace
k3s_server_disable_traefik: true
k3s_server_disable_servicelb: true

# Network configuration
k3s_server_flannel_backend: "vxlan"
k3s_server_cluster_cidr: "10.42.0.0/16"
k3s_server_service_cidr: "10.43.0.0/16"
k3s_server_cluster_dns: "10.43.0.10"
k3s_server_cluster_domain: "cluster.local"

# WSL-specific settings
k3s_server_wsl_specific: true
k3s_server_bind_address: "0.0.0.0"

# Resource limits
k3s_server_node_name: "{{ ansible_hostname }}"
k3s_server_node_labels: []
k3s_server_node_taints: []

# Additional features
k3s_server_enable_metrics_server: true

# Testing configuration
k3s_server_testing: false
k3s_server_mock_token: "K10aec3d6cfdad915d2c41a9f4cf1c319add2222f97d154addd1a8d0e890::server:mock-token-for-testing"
k3s_server_skip_service_check: false
k3s_server_skip_download: false  # Set to true during testing to avoid actual downloads
k3s_server_skip_service: false   # Set to true during testing to avoid actual service management
