---
- name: Check if K3s binary exists
  ansible.builtin.stat:
    path: "{{ k3s_server_install_dir }}/k3s"
  register: k3s_binary

- name: Download K3s binary
  ansible.builtin.get_url:
    url: "{{ k3s_server_release_url }}"
    dest: "{{ k3s_server_install_dir }}/k3s"
    mode: '0755'
    owner: root
    group: root
  when: not k3s_binary.stat.exists
  become: true

- name: Create K3s service file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: "{{ k3s_server_systemd_dir }}/{{ k3s_server_service_name }}.service"
    mode: '0644'
    owner: root
    group: root
  vars:
    k3s_exec_command: "server --config {{ k3s_server_config_file }}"
  notify:
    - Restart K3s
  become: true

- name: Create K3s systemd environment file
  ansible.builtin.template:
    src: k3s.env.j2
    dest: "{{ k3s_server_systemd_dir }}/{{ k3s_server_service_name }}.env"
    mode: '0644'
    owner: root
    group: root
  notify:
    - Restart K3s
  become: true

- name: Start and enable K3s service
  ansible.builtin.systemd:
    name: "{{ k3s_server_service_name }}"
    state: started
    enabled: true
    daemon_reload: true
  become: true
