---
- name: Check testing mode
  ansible.builtin.debug:
    msg: "Running in test mode with config_dir: {{ k3s_server_config_dir }}"
  when: k3s_server_testing | bool

- name: Verify required variables
  ansible.builtin.assert:
    that:
      - k3s_server_config_dir is defined
      - k3s_server_data_dir is defined
    fail_msg: "Required variables are not set"
    success_msg: "All required variables are present"

- name: Log variable verification status
  ansible.builtin.debug:
    msg: "Variable verification status: {{ k3s_server_config_dir }}, {{ k3s_server_data_dir }}"

- name: Validate variable verification
  ansible.builtin.assert:
    that:
      - k3s_server_config_dir is defined
      - k3s_server_data_dir is defined
    fail_msg: "Variable verification failed"
