---
- name: Include prerequisites tasks
  ansible.builtin.include_tasks:
    file: prerequisites.yml
    apply:
      tags:
        - prerequisites

- name: Include installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags:
        - install

- name: Include configuration tasks
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      tags:
        - configure

- name: Include verification tasks
  ansible.builtin.include_tasks:
    file: verify.yml
    apply:
      tags:
        - verify
