---
- name: Include prerequisites tasks
  include_tasks: prerequisites.yml
  tags:
    - k3s
    - k3s_server
    - prerequisites

- name: Include install tasks
  include_tasks: install.yml
  tags:
    - k3s
    - k3s_server
    - install

- name: Include configuration tasks
  include_tasks: configure.yml
  tags:
    - k3s
    - k3s_server
    - configure

- name: Include verification tasks
  include_tasks: verify.yml
  tags:
    - k3s
    - k3s_server
    - verify
