---
- name: Setup test environment
  when: k3s_server_testing | bool
  block:
    - name: Mock k3s binary path
      ansible.builtin.set_fact:
        k3s_server_binary: "/tmp/k3s-test/usr/local/bin/k3s"

    - name: Mock k3s server paths
      ansible.builtin.set_fact:
        k3s_server_config_dir: "/tmp/k3s-test/etc/rancher/k3s"
        k3s_server_data_dir: "/tmp/k3s-test/var/lib/rancher/k3s"

    - name: Mock systemd paths
      ansible.builtin.set_fact:
        k3s_server_service_file: "/tmp/k3s-test/etc/systemd/system/k3s.service"

    - name: Create mock systemd service file
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Lightweight Kubernetes (K3s) - Server
          Documentation=https://k3s.io
          After=network-online.target

          [Service]
          Type=notify
          ExecStart=/usr/local/bin/k3s server
          KillMode=process
          Delegate=yes
          LimitNOFILE=1048576
          LimitNPROC=infinity
          LimitCORE=infinity
          TasksMax=infinity
          TimeoutStartSec=0
          Restart=always
          RestartSec=5s

          [Install]
          WantedBy=multi-user.target
        dest: "{{ k3s_server_service_file }}"
        mode: '0644'
      when: not ansible_check_mode

    - name: Log test environment setup status
      ansible.builtin.debug:
        msg: "Test environment setup status: {{ k3s_server_binary }}, {{ k3s_server_config_dir }}, {{ k3s_server_data_dir }}, {{ k3s_server_service_file }}"

    - name: Validate test environment setup
      ansible.builtin.assert:
        that:
          - k3s_server_binary is defined
          - k3s_server_config_dir is defined
          - k3s_server_data_dir is defined
          - k3s_server_service_file is defined
        fail_msg: "Test environment setup failed"
