---
- name: Wait for K3s server to be ready
  ansible.builtin.command: kubectl --kubeconfig={{ k3s_server_kubeconfig_file }} get nodes
  register: node_status
  until: node_status.rc == 0
  retries: 24
  delay: 5
  changed_when: false
  become: true
  ignore_errors: "{{ k3s_server_testing }}"

- name: Get node status
  ansible.builtin.command: kubectl --kubeconfig={{ k3s_server_kubeconfig_file }} get nodes -o wide
  register: nodes_status
  changed_when: false
  become: true

- name: Display node status
  ansible.builtin.debug:
    var: nodes_status.stdout_lines

- name: Check core components status
  ansible.builtin.command: kubectl --kubeconfig={{ k3s_server_kubeconfig_file }} get pods -A
  register: pods_status
  changed_when: false
  become: true

- name: Display core components status
  ansible.builtin.debug:
    var: pods_status.stdout_lines

- name: Verify K3s server service is running
  ansible.builtin.systemd:
    name: "{{ k3s_server_service_name }}"
    state: started
    enabled: true
  become: true
  register: k3s_service_status
  ignore_errors: "{{ k3s_server_testing }}"

- name: Show K3s service status
  ansible.builtin.debug:
    var: k3s_service_status
