---
# Verification tasks for K3s agent

# Wait for K3s agent to be ready
- name: Wait for K3s agent to be ready
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
  register: k3s_agent_status
  until: k3s_agent_status.status.ActiveState == "active"
  retries: 12
  delay: 5
  when: not ansible_check_mode

- name: Skip verification in check mode
  ansible.builtin.debug:
    msg: "Skipping verification in check mode"
  when: ansible_check_mode

- name: Verify K3s agent version
  ansible.builtin.command: k3s --version
  register: k3s_version_output
  changed_when: false
  when: not ansible_check_mode

- name: Verify the node can connect to the server
  ansible.builtin.shell: set -o pipefail && k3s crictl info | grep -q RuntimeReady
  register: k3s_node_connection
  until: k3s_node_connection is success
  retries: 6
  delay: 10
  changed_when: false
  args:
    executable: /bin/bash
  when: not ansible_check_mode

- name: Show K3s version
  ansible.builtin.debug:
    var: k3s_version_output.stdout
  when: not ansible_check_mode and k3s_version_output is defined
