---
# Default values for the jetson_setup role
# These are used for testing and can be overridden in the playbook

# Required locales to be generated
jetson_setup_required_locales:
  - "en_US.UTF-8"
  - "en_GB.UTF-8"

# Default CUDA version
jetson_setup_cuda_version: "11.4"

# Default ML libraries to install
jetson_setup_ml_libraries:
  - nvidia-tensorrt
  - nvidia-cuda-dev
  - nvidia-cuda-toolkit

# Default monitoring tools
jetson_setup_monitoring_packages:
  - prometheus-node-exporter
  - collectd

# Default Python ML packages
jetson_setup_python_ml_packages:
  - tensorflow
  - pytorch
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter

# Default container runtime
jetson_setup_container_runtime: "docker"

# Default power mode
jetson_setup_power_mode: "balanced"
