---
# NVIDIA Jetson AGX Orin Configuration

# System optimization
jetson_hostname: "jetson-agx-orin"
jetson_timezone: "UTC"
jetson_locale: "en_US.UTF-8"
jetson_swap_size_mb: 8192

# Power mode settings
# Options: MAXN, 30W, 25W, 20W, 15W, 10W
jetson_power_mode: "MAXN"

# GPU memory settings (in MB)
jetson_gpu_memory: 8192

# CUDA and ML libraries versions
cuda_version: "11.4"
cudnn_version: "8.6"
tensorrt_version: "8.5.2"
opencv_version: "4.6.0"

# Container runtime settings
nvidia_container_runtime: true
nvidia_docker_repo_url: "https://nvidia.github.io/nvidia-docker/ubuntu22.04/nvidia-docker.list"
nvidia_docker_repo_gpg_key: "https://nvidia.github.io/nvidia-docker/gpgkey"

# Python setup for ML
python_version: "3.10"
python_venv_dir: "/opt/ml-env"
python_packages:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - torch
  - torchvision
  - tensorflow
  - jupyterlab

# System packages
system_packages:
  - build-essential
  - git
  - cmake
  - python3-pip
  - python3-dev
  - python3-venv
  - lm-sensors
  - htop
  - iotop
  - nvtop
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
