---
- name: Initial Setup for Homelab Nodes
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check connectivity to all nodes
      ansible.builtin.ping:
      register: ping_result

    - name: Verify all nodes are reachable
      ansible.builtin.debug:
        msg: "Node {{ inventory_hostname }} is reachable"
      when: ping_result is success

    - name: Check system information
      ansible.builtin.setup:
        gather_subset:
          - min

  roles:
    - role: common
      tags: always

  post_tasks:
    - name: Verify base configuration
      ansible.builtin.debug:
        msg: "Common configuration applied to {{ inventory_hostname }}"

- name: Configure K3s Control Nodes
  hosts: control_nodes
  become: true
  gather_facts: true
  roles:
    - role: k3s_server
      tags: k3s_control

  tasks:
    - name: Install Operator Lifecycle Manager (OLM)
      block:
        - name: Download OLM installer script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/install.sh
            dest: /tmp/install-olm.sh
            mode: '0755'

        - name: Execute OLM installation
          ansible.builtin.command: /tmp/install-olm.sh
          register: olm_install
          changed_when: olm_install.rc == 0
          failed_when: olm_install.rc != 0

        - name: Wait for OLM deployments to be ready
          kubernetes.core.k8s_info:
            api_version: apps/v1
            kind: Deployment
            namespace: olm
            wait: yes
            wait_timeout: 300
          register: olm_deployments

    - name: Install cert-manager operator
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: cert-manager
            namespace: operators
          spec:
            channel: stable
            name: cert-manager
            source: operatorhubio-catalog
            sourceNamespace: olm

    - name: Install Traefik operator
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: traefik
            namespace: operators
          spec:
            channel: stable
            name: traefik-operator
            source: operatorhubio-catalog
            sourceNamespace: olm

  post_tasks:
    - name: Verify K3s Server and Operator Installation
      block:
        - name: Check K3s configuration
          ansible.builtin.command: k3s check-config
          register: k3s_check
          changed_when: false
          failed_when: k3s_check.rc not in [0, 1]

        - name: Verify operator installations
          kubernetes.core.k8s_info:
            api_version: operators.coreos.com/v1alpha1
            kind: ClusterServiceVersion
            namespace: operators
          register: installed_operators

        - name: Report K3s and Operator Status
          ansible.builtin.debug:
            msg: "K3s server and operators configured on {{ inventory_hostname }}"

- name: Configure AI Nodes
  hosts: ai_nodes
  become: true
  gather_facts: true
  roles:
    - role: jetson_setup
      tags: ai_setup
    - role: k3s_agent
      tags: k3s_agent

  post_tasks:
    - name: Verify AI Node Setup
      ansible.builtin.debug:
        msg: "AI node configuration completed on {{ inventory_hostname }}"

- name: Configure Home Automation Nodes
  hosts: home_automation
  become: true
  gather_facts: true
  roles:
    - role: home_assistant_integration
      tags: home_automation

  post_tasks:
    - name: Verify Home Automation Setup
      ansible.builtin.debug:
        msg: "Home automation integration completed on {{ inventory_hostname }}"

- name: Finalize All Node Setup
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Verify all services are running
      ansible.builtin.command: systemctl is-system-running
      register: system_status
      changed_when: false
      failed_when: system_status.rc not in [0, 1]

    - name: Verify operator health
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        namespace: operators
      register: operator_status
      when: "'control_nodes' in group_names"
      failed_when: false

    - name: Report final status
      ansible.builtin.debug:
        msg: "Initial setup completed on {{ inventory_hostname }} - System status: {{ system_status.stdout }} {% if 'control_nodes' in group_names %}- Operators status: {{ operator_status.resources | length }} operators installed{% endif %}"
