---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      connection: local
platforms:
  - name: pulumi-test
    groups:
      - pulumi
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_VERBOSITY: 1
    PULUMI_CONFIG_PASSPHRASE: "${PULUMI_CONFIG_PASSPHRASE:-test-passphrase}"
    PULUMI_BACKEND_URL: "file:///tmp/pulumi-test-state"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: testinfra
  directory: ../tests
  options:
    v: 1
scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
