---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install required packages
      ansible.builtin.package:
        name:
          - curl
          - python3
          - python3-pip
        state: present

    - name: Create test directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "/etc/systemd/system"
        - "/usr/local/bin"

    - name: Set up testing environment
      ansible.builtin.debug:
        msg: "Preparing test environment for k3s_server role"
