---
- name: Restart K3s
  ansible.builtin.systemd:
    name: "{{ k3s_server_service_name }}"
    state: restarted
    daemon_reload: true
  become: true

- name: Stop K3s
  ansible.builtin.systemd:
    name: "{{ k3s_server_service_name }}"
    state: stopped
    daemon_reload: true
  become: true

- name: Start K3s
  ansible.builtin.systemd:
    name: "{{ k3s_server_service_name }}"
    state: started
    daemon_reload: true
  become: true
