---
- name: restart k3s
  systemd:
    name: "{{ k3s_service_name }}"
    state: restarted
    daemon_reload: yes
  become: true

- name: stop k3s
  systemd:
    name: "{{ k3s_service_name }}"
    state: stopped
  become: true

- name: start k3s
  systemd:
    name: "{{ k3s_service_name }}"
    state: started
    enabled: yes
  become: true
