---
# K3s server information
k3s_agent_server_url: "https://192.168.0.51:6443"
k3s_agent_token: ""  # To be specified at runtime

# K3s version
k3s_agent_version: "v1.28.4+k3s2"
k3s_agent_installer_url: "https://get.k3s.io"

# K3s agent configuration
k3s_agent_flags:
  - "--node-label=jetson.nvidia.com/gpu=true"
  - "--node-label=topology.kubernetes.io/region=homelab"
  - "--node-label=topology.kubernetes.io/zone=office"
  - "--kubelet-arg=feature-gates=DevicePlugins=true"
  - "--kubelet-arg=volume-plugin-dir=/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
  - "--container-runtime-endpoint=unix:///run/containerd/containerd.sock"

# NVIDIA GPU configuration
k3s_agent_nvidia_container_runtime_installed: false
k3s_agent_nvidia_docker_repo_url: "https://nvidia.github.io/nvidia-docker/ubuntu22.04/nvidia-docker.list"
k3s_agent_nvidia_docker_repo_gpg_key: "https://nvidia.github.io/nvidia-docker/gpgkey"

# Node configuration
k3s_agent_node_hostname: "{{ ansible_hostname }}"
k3s_agent_node_ip: "{{ ansible_default_ipv4.address }}"

# Directory for K3s configuration
k3s_agent_config_dir: "/etc/rancher/k3s"
k3s_agent_service_file: "/etc/ansible.builtin.systemd/system/k3s-agent.service"
