---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - python3-pip
        state: present
        update_cache: true

    - name: Mock system information for testing
      ansible.builtin.set_fact:
        ansible_distribution: "Ubuntu"
        ansible_distribution_version: "22.04"
        ansible_architecture: "amd64"
        ansible_os_family: "Debian"

    - name: Mock nvidia-smi command for testing
      ansible.builtin.copy:
        dest: /usr/bin/nvidia-smi
        content: |
          #!/bin/bash
          echo "NVIDIA-SMI 535.54.03   Driver Version: 535.54.03   CUDA Version: 12.2"
          exit 0
        mode: '0755'
