---
- name: Converge
  hosts: all
  become: true
  vars:
    home_assistant_integration_testing: true
    test_base_dir: "/tmp/home-assistant-test"
    home_assistant_integration_user: "homeassistant"

    # MQTT Integration
    home_assistant_integration_enable_mqtt: true
    home_assistant_integration_mqtt_accept_license: true
    home_assistant_integration_mqtt_broker_host: "localhost"
    home_assistant_integration_mqtt_broker_port: 1883
    home_assistant_integration_mqtt_username: "homeassistant"
    home_assistant_integration_mqtt_password: "test-password"

    # InfluxDB Integration
    home_assistant_integration_enable_influxdb: true
    home_assistant_integration_influxdb_accept_license: true
    home_assistant_integration_influxdb_host: "localhost"
    home_assistant_integration_influxdb_port: 8086

    # Voice Assistant Integration
    home_assistant_integration_enable_voice_assistant: true
    home_assistant_integration_voice_assistant_accept_license: true
    home_assistant_integration_voice_assistant_addon: "a0d7b954_rhasspy"
    home_assistant_integration_voice_assistant_type: "local"

    # SSH Integration
    home_assistant_integration_enable_ssh: true
    home_assistant_integration_ssh_accept_license: true
    home_assistant_integration_ssh_public_key: "ssh-rsa AAAA... molecule-test-key"

    override_paths:
      config_dir: "{{ test_base_dir }}/config"
      hassio_dir: "{{ test_base_dir }}/usr/share/hassio"

  pre_tasks:
    - name: Create test user
      ansible.builtin.user:
        name: "{{ home_assistant_integration_user }}"
        state: present
        system: true
        create_home: true
        shell: /bin/bash

    - name: Create test directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "{{ '0700' if '.ssh' in item else '0755' }}"
        owner: "{{ home_assistant_integration_user }}"
        group: "{{ home_assistant_integration_user }}"
      loop:
        - "{{ test_base_dir }}/config"
        - "{{ test_base_dir }}/config/integrations"
        - "{{ test_base_dir }}/config/.ssh"
        - "{{ test_base_dir }}/usr/share/hassio"
        - "{{ test_base_dir }}/usr/share/hassio/addons"
        - "{{ test_base_dir }}/usr/share/hassio/addons/core_mosquitto"
        - "{{ test_base_dir }}/usr/share/hassio/addons/5ba9ddb2_influxdb"
        - "{{ test_base_dir }}/usr/share/hassio/addons/a0d7b954_ssh"
        - "{{ test_base_dir }}/usr/share/hassio/addons/a0d7b954_rhasspy"

    - name: Create mock config files
      ansible.builtin.copy:
        content: "# Mock Home Assistant config file for testing"
        dest: "{{ test_base_dir }}/config/configuration.yaml"
        mode: '0644'
        owner: "{{ home_assistant_integration_user }}"
        group: "{{ home_assistant_integration_user }}"

  roles:
    - role: home_assistant_integration

  post_tasks:
    - name: Show test results
      ansible.builtin.debug:
        msg: "Home Assistant integration role converge completed successfully"
