---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3-pip
          - openssh-server
          - openssl
        state: present
        update_cache: true

    - name: Create home assistant user
      ansible.builtin.user:
        name: homeassistant
        state: present
        system: true
        create_home: true
        shell: /bin/bash

    - name: Create required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "/usr/share/hassio"
        - "/usr/share/hassio/addons"
        - "/usr/local/bin"

    - name: Create mock hassio command
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          echo "Mock hassio command for testing"
          exit 0
        dest: "/usr/local/bin/hassio"
        mode: '0755'
