---
- name: Set facts for testing environment
  ansible.builtin.set_fact:
    ansible_os_family: "{{ ansible_os_family | default('Debian') }}"
  when: home_assistant_integration_testing | default(false) | bool

- name: Include variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Set base directories
  ansible.builtin.set_fact:
    config_base_dir: "{{ config_base_dir | default('/config') }}"
    hassio_base_dir: "{{ hassio_base_dir | default('/usr/share/hassio') }}"
    is_testing: "{{ home_assistant_integration_testing | default(false) | bool }}"
    home_assistant_integration_user: "{{ home_assistant_integration_user | default('homeassistant') }}"

- name: Set file ownership variables
  ansible.builtin.set_fact:
    file_owner: "{{ is_testing | ternary(ansible_user_id, home_assistant_integration_user) }}"
    file_group: "{{ is_testing | ternary(ansible_user_gid, home_assistant_integration_user) }}"

- name: Create integrations directory
  ansible.builtin.file:
    path: "{{ config_base_dir }}/integrations"
    state: directory
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: "0755"
  become: "{{ not is_testing }}"

- name: Create SSH directory
  ansible.builtin.file:
    path: "{{ config_base_dir }}/.ssh"
    state: directory
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: "0700"
  become: "{{ not is_testing }}"

- name: Configure Home Assistant MQTT integration
  ansible.builtin.include_tasks: mqtt.yml
  when: home_assistant_integration_enable_mqtt | default(false) | bool

- name: Configure Home Assistant SSH integration
  ansible.builtin.include_tasks: ssh.yml
  when: home_assistant_integration_enable_ssh | default(false) | bool

- name: Configure Home Assistant InfluxDB integration
  ansible.builtin.include_tasks: influxdb.yml
  when: home_assistant_integration_enable_influxdb | default(false) | bool

- name: Configure Home Assistant Voice Assistant integration
  ansible.builtin.include_tasks: voice_assistant.yml
  when: home_assistant_integration_enable_voice_assistant | default(false) | bool
