---
# Main tasks file for home_assistant_integration role

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family is defined
  ignore_errors: yes

- name: Check if Home Assistant is installed
  stat:
    path: "/usr/share/hassio"
  register: ha_installed
  become: true

- name: Fail if Home Assistant is not installed
  fail:
    msg: "Home Assistant is not installed. Please install Home Assistant OS first."
  when: not ha_installed.stat.exists

- name: Create Home Assistant configuration directory
  file:
    path: /config
    state: directory
    owner: homeassistant
    group: homeassistant
    mode: '0755'
  become: true

- name: Generate Home Assistant API token
  uri:
    url: "http://localhost:8123/auth/token"
    method: POST
    body_format: json
    body:
      client_id: "ansible-automation"
      client_name: "Ansible Automation"
    status_code: 200
  register: token_response
  become: false
  ignore_errors: yes

- name: Set Home Assistant token
  set_fact:
    home_assistant_token: "{{ token_response.json.access_token }}"
  when: token_response is success
  ignore_errors: yes

- name: Include MQTT setup tasks
  include_tasks: mqtt.yml

- name: Include InfluxDB setup tasks
  include_tasks: influxdb.yml

- name: Include SSH setup tasks
  include_tasks: ssh.yml
  when: enable_ssh | bool

- name: Include voice assistant setup tasks
  include_tasks: voice_assistant.yml
  when: enable_voice_assistant | bool
