---
# Tasks for MQTT configuration

- name: Install Mosquitto MQTT client
  shell: ha add-on install core_mosquitto
  become: true
  ignore_errors: yes
  register: mqtt_install
  changed_when: "'Installed' in mqtt_install.stdout"

- name: Configure Mosquitto MQTT add-on
  template:
    src: mosquitto.j2
    dest: /config/mosquitto.yaml
    owner: homeassistant
    group: homeassistant
    mode: '0644'
  become: true
  notify: restart mosquitto

- name: Configure MQTT integration in Home Assistant
  template:
    src: mqtt.j2
    dest: /config/integrations/mqtt.yaml
    owner: homeassistant
    group: homeassistant
    mode: '0644'
  become: true
  notify: restart home assistant

- name: Ensure MQTT integration is included in configuration
  lineinfile:
    path: /config/configuration.yaml
    line: "mqtt: !include integrations/mqtt.yaml"
    state: present
  become: true
  notify: reload home assistant configuration

- name: Start Mosquitto MQTT add-on
  shell: ha add-on start core_mosquitto
  become: true
  ignore_errors: yes
