---
# Tasks for Voice Assistant configuration

- name: Install Voice Assistant add-on
  ansible.builtin.command:
    cmd: "hassio addons install {{ home_assistant_integration_voice_assistant_addon }}"
  register: voice_assistant_install
  failed_when: false
  changed_when: "'already installed' not in voice_assistant_install.stderr"
  when: not is_testing

- name: Accept Voice Assistant add-on license
  ansible.builtin.lineinfile:
    path: "{{ hassio_base_dir }}/addons/{{ home_assistant_integration_voice_assistant_addon }}/options.json"
    regexp: '"license": false'
    line: '"license": true'
    create: true
    mode: '0644'
  when: home_assistant_integration_voice_assistant_accept_license | bool

- name: Configure Voice Assistant integration
  ansible.builtin.template:
    src: voice_assistant.j2
    dest: "{{ config_base_dir }}/integrations/voice_assistant.yaml"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: '0644'
  notify: Reload Home Assistant Configuration

- name: Configure Wyoming integration
  ansible.builtin.template:
    src: wyoming.j2
    dest: "{{ config_base_dir }}/integrations/wyoming.yaml"
    owner: "{{ file_owner }}"
    group: "{{ file_group }}"
    mode: '0644'
  notify: Reload Home Assistant Configuration
  when: home_assistant_integration_voice_assistant_type == "local"

- name: Start Voice Assistant add-on
  ansible.builtin.command:
    cmd: "hassio addons start {{ home_assistant_integration_voice_assistant_addon }}"
  register: voice_assistant_start
  failed_when: false
  changed_when: "'already running' not in voice_assistant_start.stderr"
  when: not is_testing

- name: Mock starting Voice Assistant add-on in test mode
  ansible.builtin.debug:
    msg: "Would start Voice Assistant add-on in test mode"
  when: is_testing
