name: Ansible Role Tests

on:
  push:
    paths:
      - 'ansible/**'
  pull_request:
    paths:
      - 'ansible/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule molecule-docker docker pytest-testinfra

      - name: Run Molecule tests
        run: |
          cd ansible/roles/k3s_server
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
