name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 'Enable Debug Mode'
        default: false
      roles:
        type: string
        description: 'Comma-separated roles to test'
        default: 'all'

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e .[dev]; fi
          
      - name: Run pre-commit
        run: pre-commit run --all-files
        env:
          SKIP: molecule-lint,pulumi-validate

  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint --force-color

  molecule:
    name: Molecule Test - ${{ matrix.role }}
    runs-on: ubuntu-latest
    needs: ansible-lint
    strategy:
      fail-fast: false
      matrix:
        role:
          - k3s_server
          - k3s_agent
          - common
          - jetson_setup
          - home_assistant_integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run Molecule tests
        run: |
          python -m molecule test -s default
        env:
          MOLECULE_ROLE: ${{ matrix.role }}
          ANSIBLE_FORCE_COLOR: "1"

      - name: Generate JUnit Report
        if: always()
        run: |
          python -m molecule test -s default --destroy=never --reporter junit --out junit-${{ matrix.role }}.xml
        env:
          MOLECULE_ROLE: ${{ matrix.role }}
          ANSIBLE_FORCE_COLOR: "1"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.role }}
          path: junit-${{ matrix.role }}.xml

  pulumi-test:
    name: Pulumi Test - ${{ matrix.stack }}
    runs-on: ubuntu-latest
    needs: pre-commit
    strategy:
      fail-fast: false
      matrix:
        stack:
          - cluster-setup
          - core-services
          - storage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'pulumi/${{ matrix.stack }}/package-lock.json'

      - name: Install dependencies
        run: |
          cd pulumi/${{ matrix.stack }}
          npm ci

      - name: Run TypeScript validation
        run: |
          cd pulumi/${{ matrix.stack }}
          npx tsc --noEmit

      - name: Run unit tests
        run: |
          cd pulumi/${{ matrix.stack }}
          npm test

  molecule-pulumi:
    name: Molecule Pulumi Integration Test
    runs-on: ubuntu-latest
    needs: [molecule, pulumi-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run Molecule tests with Pulumi integration
        run: |
          cd pulumi
          python -m molecule test -s default
        env:
          ANSIBLE_FORCE_COLOR: "1"
          PULUMI_CONFIG_PASSPHRASE: "test-passphrase"
          PULUMI_BACKEND_URL: "file:///tmp/pulumi-test-state"

  test-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs: [molecule, pulumi-test, molecule-pulumi]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: test-results

      - name: Generate combined test report
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: 'test-results/**/*.xml'
          reporter: jest-junit
          fail-on-error: false
